# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xOrUkxPa5X8lRvzKcmEZ0LgUgw6ULqL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (9, 5)
pd.set_option('display.max_columns', None)

df = pd.read_csv('/seasonal_agriculture_performance_dataset.csv')
print("Shape:", df.shape)
df.head()

df.info()

df.describe().T

for col in ['Season', 'State', 'Crop', 'Irrigation_Method']:
    print(f"{col} ({df[col].nunique()}): {sorted(df[col].unique())}\n")

missing = df.isnull().sum()
print(missing[missing > 0])
print("\nTotal duplicate rows:", df.duplicated().sum())

cols_with_na = ['Rainfall_mm', 'Soil_Moisture_pct', 'Yield_Tonnes_Ha']

for col in cols_with_na:
    df[col] = df.groupby('Season')[col].transform(lambda x: x.fillna(x.median()))

print("Remaining missing values:", df.isnull().sum().sum())

# Sanity checks on ranges (basic outlier/consistency scan)
print(df[['Soil_pH','Humidity_pct','Yield_Tonnes_Ha','Profit_INR']].describe().T[['min','max','mean']])

fig, axes = plt.subplots(1, 2, figsize=(14,5))
sns.countplot(data=df, x='Season', order=['Kharif','Rabi','Zaid'], ax=axes[0], palette='viridis')
axes[0].set_title('Number of Farm Records per Season')

crop_season = pd.crosstab(df['Crop'], df['Season'])
sns.heatmap(crop_season, annot=True, fmt='d', cmap='YlGnBu', ax=axes[1])
axes[1].set_title('Crop Distribution across Seasons')
plt.tight_layout()
plt.show()

perf = df.groupby('Season')[['Yield_Tonnes_Ha','Production_Tonnes','Profit_INR']].agg(['mean','median'])
perf.round(2)

fig, axes = plt.subplots(1, 3, figsize=(16,5))
order = ['Kharif','Rabi','Zaid']

sns.boxplot(data=df, x='Season', y='Yield_Tonnes_Ha', order=order, ax=axes[0], palette='Set2', showfliers=False)
axes[0].set_title('Yield (Tonnes/Ha) by Season')

sns.boxplot(data=df, x='Season', y='Production_Tonnes', order=order, ax=axes[1], palette='Set2', showfliers=False)
axes[1].set_title('Production (Tonnes) by Season')

sns.boxplot(data=df, x='Season', y='Profit_INR', order=order, ax=axes[2], palette='Set2', showfliers=False)
axes[2].axhline(0, color='red', linestyle='--', linewidth=1)
axes[2].set_title('Profit (INR) by Season')

plt.tight_layout()
plt.show()

loss_share = df.assign(Loss=df['Profit_INR'] < 0).groupby('Season')['Loss'].mean().reindex(order) * 100
print("Percentage of loss-making farms by season:")
print(loss_share.round(1))

env_cols = ['Rainfall_mm','Avg_Temperature_C','Humidity_pct','Sunlight_Hours_Day','Soil_Moisture_pct','Soil_pH']
env_summary = df.groupby('Season')[env_cols].mean().reindex(order)
env_summary.round(2)

fig, axes = plt.subplots(2, 3, figsize=(16,9))
axes = axes.flatten()
for i, col in enumerate(env_cols):
    sns.barplot(x=env_summary.index, y=env_summary[col], ax=axes[i], palette='crest')
    axes[i].set_title(col)
    axes[i].set_xlabel('')
plt.tight_layout()
plt.show()

res_cols = ['Fertilizer_kg_ha','Pesticide_Litre_ha','Nitrogen_kg_ha','Phosphorus_kg_ha',
            'Potassium_kg_ha','Water_Used_m3','Water_Efficiency_t_per_1000m3']
res_summary = df.groupby('Season')[res_cols].mean().reindex(order)
res_summary.round(2)

fig, axes = plt.subplots(1, 2, figsize=(14,5))
sns.barplot(x=res_summary.index, y=res_summary['Water_Used_m3'], ax=axes[0], palette='mako')
axes[0].set_title('Average Water Used (m³) by Season')

sns.barplot(x=res_summary.index, y=res_summary['Water_Efficiency_t_per_1000m3'], ax=axes[1], palette='mako')
axes[1].set_title('Water Efficiency (Tonnes per 1000 m³) by Season')
plt.tight_layout()
plt.show()

# Irrigation method efficiency across seasons
irrig_eff = df.pivot_table(index='Irrigation_Method', columns='Season',
                            values='Water_Efficiency_t_per_1000m3', aggfunc='mean').reindex(columns=order)
irrig_eff.round(3)

econ_cols = ['Total_Cost_INR','Revenue_INR','Profit_INR','Market_Price_INR_Tonne']
econ_summary = df.groupby('Season')[econ_cols].mean().reindex(order)
econ_summary.round(0)

fig, ax = plt.subplots(figsize=(9,5))
econ_summary[['Total_Cost_INR','Revenue_INR']].plot(kind='bar', ax=ax, color=['#e76f51','#2a9d8f'])
ax.set_title('Average Cost vs Revenue by Season')
ax.set_ylabel('INR')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

numeric_df = df.select_dtypes(include=np.number)
corr = numeric_df.corr()

plt.figure(figsize=(14,10))
sns.heatmap(corr, cmap='coolwarm', center=0, annot=False)
plt.title('Correlation Heatmap - All Numeric Variables')
plt.tight_layout()
plt.show()

print("Top correlations with Yield_Tonnes_Ha:")
print(corr['Yield_Tonnes_Ha'].sort_values(ascending=False).head(6))
print("\nTop correlations with Profit_INR:")
print(corr['Profit_INR'].sort_values(ascending=False).head(6))

crop_profit = df.pivot_table(index='Crop', columns='Season', values='Profit_INR', aggfunc='mean').reindex(columns=order)
crop_profit_sorted = crop_profit.reindex(crop_profit.mean(axis=1).sort_values(ascending=False).index)

plt.figure(figsize=(9,6))
sns.heatmap(crop_profit_sorted, annot=True, fmt='.0f', cmap='RdYlGn', center=0)
plt.title('Average Profit (INR) by Crop and Season')
plt.tight_layout()
plt.show()

crop_yield = df.pivot_table(index='Crop', columns='Season', values='Yield_Tonnes_Ha', aggfunc='mean').reindex(columns=order)
crop_yield.round(2)

state_profit = df.pivot_table(index='State', columns='Season', values='Profit_INR', aggfunc='mean').reindex(columns=order)
plt.figure(figsize=(9,6))
sns.heatmap(state_profit, annot=True, fmt='.0f', cmap='RdYlGn', center=0)
plt.title('Average Profit (INR) by State and Season')
plt.tight_layout()
plt.show()

risk_summary = df.groupby('Season')['Disease_Pest_Risk_pct'].mean().reindex(order)
print(risk_summary.round(2))

plt.figure(figsize=(7,5))
sns.boxplot(data=df, x='Season', y='Disease_Pest_Risk_pct', order=order, palette='Reds')
plt.title('Disease/Pest Risk (%) by Season')
plt.tight_layout()
plt.show()

groups_yield = [g['Yield_Tonnes_Ha'].values for _, g in df.groupby('Season')]
f_yield, p_yield = stats.f_oneway(*groups_yield)

groups_profit = [g['Profit_INR'].values for _, g in df.groupby('Season')]
f_profit, p_profit = stats.f_oneway(*groups_profit)

print(f"ANOVA on Yield  -> F = {f_yield:.2f}, p = {p_yield:.5f}")
print(f"ANOVA on Profit -> F = {f_profit:.2f}, p = {p_profit:.5f}")

def flag_outliers(group):
    q1, q3 = group['Profit_INR'].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
    return (group['Profit_INR'] < lower) | (group['Profit_INR'] > upper)

df['Profit_Outlier'] = df.groupby('Season', group_keys=False).apply(flag_outliers)
outlier_counts = df.groupby('Season')['Profit_Outlier'].sum().reindex(order)
print("Number of extreme-profit outlier farms per season:")
print(outlier_counts)

df[df['Profit_Outlier']][['Farm_ID','State','Crop','Season','Yield_Tonnes_Ha','Profit_INR']].sort_values('Profit_INR').head(10)